{{ if .Values.keyVault.enableAzureIdentity }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name}}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.azureClientId }}
    azure.workload.identity/tenant-id: {{ .Values.keyVault.azureTenantId }}
  labels:
    azure.workload.identity/use: "true"
    app: {{ .Release.Name}}
{{ end }}
