// ⚠️  WARNING: DO NOT EDIT THIS FILE WITH COPILOT OR AI TOOLS
// This ESLint configuration file should only be modified by human developers
// AI tools may not understand the complex rule interactions and project-specific requirements
// For rule changes, please consult the development team or project maintainer

import js from '@eslint/js';
import globals from 'globals';
import vueParser from 'vue-eslint-parser';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import vuePlugin from 'eslint-plugin-vue';
import importPlugin from 'eslint-plugin-import';
import sortPlugin from 'eslint-plugin-simple-import-sort';
import unusedImports from 'eslint-plugin-unused-imports';
import prettier from 'eslint-config-prettier';

// Note: keep Prettier last so it turns off conflicting ESLint formatting rules
export default [
  // Base JS recommendations
  js.configs.recommended,
  
  // Allow JS in config files only
  {
    files: ['*.config.{js,ts}', 'vite.config.ts', 'vitest.config.ts', 'eslint.config.js'],
    languageOptions: {
      globals: {
        process: 'readonly',
        __dirname: 'readonly',
        module: 'readonly',
        require: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
  // Project-level legacy JS ignores (flat config requires root-level or separate object)
  {
    ignores: [
      // Ignore generated OpenAPI and legacy JS until migrated to TS
      'src/api/**/*.js',
      'src/tests/**/*.js',
      'src/test/**/*.js',
      'src/components/**/*.js',
      'src/composables/**/*.js',
      'src/utils/**/*.js',
      'src/store/**/*.js',
      'src/types/**/*.js',
      'src/router/**/*.js',
      'src/config/**/*.js',
      'src/main.js',
    ],
  },
  
  // TypeScript files (.ts) - primary rule set
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsParser,
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        // If you want stricter type-aware checks enable project and point to tsconfig
        // project: './tsconfig.json'
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      import: importPlugin,
      'simple-import-sort': sortPlugin,
      'unused-imports': unusedImports,
    },
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
          project: './tsconfig.json',
        },
        alias: {
          map: [['@', './src']],
          extensions: ['.ts', '.js', '.vue', '.json'],
        },
      },
    },
    rules: {
      /* Disable base rule in favor of TypeScript-specific rule */
      'no-unused-vars': 'off',
      
      /* TypeScript hygiene */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-function': 'error',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],

      /* general js/ts rules */
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-debugger': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-template': 'error',
      eqeqeq: ['error', 'always'],
      'no-eval': 'error',

      /* complexity & code-health */
      'max-len': [
        'error',
        {
          code: 120,
          tabWidth: 2,
          ignoreUrls: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
          ignoreRegExpLiterals: true,
        },
      ],
      'max-lines': ['error', { max: 500, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 100, skipBlankLines: true, skipComments: true }],
      complexity: ['error', 12],

      /* import sorting and unused imports */
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
      'unused-imports/no-unused-imports': 'error',
      // Disable to avoid duplicate reports with @typescript-eslint/no-unused-vars
      'unused-imports/no-unused-vars': 'off',

      /* import validation */
      'import/no-unresolved': 'error',
      'import/no-duplicates': 'error',
    },
  },

  // Vue Single File Components (.vue)
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
      parserOptions: {
        parser: tsParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
    },
    plugins: {
      vue: vuePlugin,
      '@typescript-eslint': tsPlugin,
      import: importPlugin,
      'simple-import-sort': sortPlugin,
      'unused-imports': unusedImports,
    },
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
          project: './tsconfig.json',
        },
        alias: {
          map: [['@', './src']],
          extensions: ['.ts', '.js', '.vue', '.json'],
        },
      },
    },
    rules: {
      /* Vue recommended best-practices */
      'vue/no-unused-components': 'error',
      'vue/require-v-for-key': 'error',
      'vue/no-use-v-if-with-v-for': 'error',
      'vue/html-quotes': ['error', 'double'],
      'vue/component-api-style': ['error', ['script-setup', 'composition']],
      'vue/no-v-html': 'error',
      'vue/multi-word-component-names': [
        'error',
        { ignores: ['App', 'Layout', 'Home', 'Login', 'Dashboard'] },
      ],

      /* Templates / formatting — keep minimal because Prettier handles most */
      'vue/max-attributes-per-line': ['error', { singleline: 3, multiline: { max: 1 } }],
      'vue/html-indent': [
        'error',
        2,
        { attribute: 1, baseIndent: 1, closeBracket: 0, alignAttributesVertically: true },
      ],

      /* TypeScript and unused imports in <script setup> */
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'unused-imports/no-unused-imports': 'error',
      // Disable to avoid duplicate reports with @typescript-eslint/no-unused-vars
      'unused-imports/no-unused-vars': 'off',

      /* import validation */
      'import/no-unresolved': 'error',
      'import/no-duplicates': 'error',

      /* File complexity rules for Vue files */
      'max-len': [
        'error',
        {
          code: 120,
          tabWidth: 2,
          ignoreUrls: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
          ignoreRegExpLiterals: true,
        },
      ],
      'max-lines': ['error', { max: 500, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 100, skipBlankLines: true, skipComments: true }],
      complexity: ['error', 12],

      /* Misc */
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // JavaScript files in src (if any) - prefer TS but allow legacy JS with warnings
  {
    files: ['src/**/*.js'],
    rules: {
      'no-restricted-syntax': [
        'warn',
        {
          selector: 'Program',
          message: 'Avoid adding new plain JavaScript files to src/. Prefer TypeScript or .vue',
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // Test files
  {
    files: ['**/*.{test,spec}.{ts,js,vue}', 'src/test/**/*.ts', 'src/tests/**/*.ts'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-function': 'off', // Allow empty mock functions in tests
      'max-len': [
        'warn',
        {
          code: 140,
          tabWidth: 2,
          ignoreUrls: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
        },
      ],
      'max-lines': 'off', // Allow large test files
      'max-lines-per-function': 'off', // Allow large test functions
      complexity: 'off', // Allow complex test scenarios
    },
  },

  // Generated API files - allow some leniency
  {
    files: ['src/api/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-vars': 'off',
    },
  },

  // Global environment / defines for composition API helpers
  {
    files: ['**/*.{ts,vue,js}'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        clearTimeout: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        Event: 'readonly',
        Node: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        btoa: 'readonly',
        process: 'readonly',
        NodeJS: 'readonly',
        defineProps: 'readonly',
        defineEmits: 'readonly',
        defineExpose: 'readonly',
        withDefaults: 'readonly',
        computed: 'readonly',
        reactive: 'readonly',
        ref: 'readonly',
        watch: 'readonly',
        watchEffect: 'readonly',
        onMounted: 'readonly',
        onUnmounted: 'readonly',
        nextTick: 'readonly',
      },
    },
  },

  // Ignore patterns
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      '*.min.js',
      'public/**',
      'src/generated/**',
      'src/shims-vue.d.ts',
      '**/*.vue.js',
    ],
  },

  // Prettier to turn off formatting rules last
  prettier,
];